-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activities
(
    id serial NOT NULL,
    user_id integer,
    project_id integer,
    entity_type character varying(50) COLLATE pg_catalog."default",
    entity_id integer,
    action character varying(100) COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attachments
(
    id serial NOT NULL,
    task_id integer,
    user_id integer,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT attachments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    entity_id integer NOT NULL,
    user_id integer NOT NULL,
    content text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    entity_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'task'::character varying,
    parent_id integer,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.datasets
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    project_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    version character varying(50) COLLATE pg_catalog."default",
    data_url text COLLATE pg_catalog."default",
    metadata jsonb,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT datasets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.experiment_datasets
(
    task_id integer NOT NULL,
    dataset_id integer NOT NULL,
    relation_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'input'::character varying,
    CONSTRAINT experiment_datasets_pkey PRIMARY KEY (task_id, dataset_id)
);

CREATE TABLE IF NOT EXISTS public.grants
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    funding_organization character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    scientific_direction character varying(255) COLLATE pg_catalog."default",
    grant_type character varying(50) COLLATE pg_catalog."default" DEFAULT 'state'::character varying,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'draft'::character varying,
    total_amount numeric(15, 2) DEFAULT 0,
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'RUB'::character varying,
    start_date date,
    end_date date,
    application_deadline date,
    principal_investigator_id integer,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT grants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hypotheses
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    project_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'proposed'::character varying,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT hypotheses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.project_grant_funding
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grant_id integer NOT NULL,
    project_id integer NOT NULL,
    section_id integer,
    allocated_amount numeric(15, 2) DEFAULT 0,
    funding_purpose text COLLATE pg_catalog."default",
    funding_start_date date,
    funding_end_date date,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_grant_funding_pkey PRIMARY KEY (id),
    CONSTRAINT unique_grant_project_section UNIQUE (grant_id, project_id, section_id)
);

CREATE TABLE IF NOT EXISTS public.project_members
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    project_id integer NOT NULL,
    user_id integer NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'participant'::character varying,
    role_id integer,
    CONSTRAINT project_members_pkey PRIMARY KEY (id),
    CONSTRAINT unique_member UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    key character varying(10) COLLATE pg_catalog."default",
    research_goal text COLLATE pg_catalog."default" DEFAULT ''::text,
    main_hypothesis text COLLATE pg_catalog."default" DEFAULT ''::text,
    novelty text COLLATE pg_catalog."default" DEFAULT ''::text,
    expected_result text COLLATE pg_catalog."default" DEFAULT ''::text,
    visibility text COLLATE pg_catalog."default" DEFAULT 'closed'::text,
    team_id integer,
    execution_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'manual'::character varying,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_system boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.sprints
(
    id serial NOT NULL,
    project_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'planned'::character varying,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    goal text COLLATE pg_catalog."default",
    CONSTRAINT sprints_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT tags_pkey PRIMARY KEY (id),
    CONSTRAINT tags_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.task_history
(
    id serial NOT NULL,
    task_id integer,
    changed_by integer,
    field_name character varying(100) COLLATE pg_catalog."default",
    old_value text COLLATE pg_catalog."default",
    new_value text COLLATE pg_catalog."default",
    changed_at timestamp without time zone DEFAULT now(),
    CONSTRAINT task_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.task_tags
(
    task_id integer NOT NULL,
    tag_id integer NOT NULL,
    CONSTRAINT task_tags_pkey PRIMARY KEY (task_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    project_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'todo'::character varying,
    priority character varying(20) COLLATE pg_catalog."default" DEFAULT 'medium'::character varying,
    assignee_id integer,
    created_by integer,
    due_date date,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    type text COLLATE pg_catalog."default",
    hypothesis_id integer,
    conclusion text COLLATE pg_catalog."default" DEFAULT ''::text,
    parameters jsonb,
    metrics jsonb,
    task_num integer,
    sprint_id integer,
    research_contribution text COLLATE pg_catalog."default" DEFAULT ''::text,
    research_method text COLLATE pg_catalog."default" DEFAULT 'experiment'::text,
    doi text COLLATE pg_catalog."default",
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team_members
(
    team_id integer NOT NULL,
    user_id integer NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" DEFAULT 'member'::character varying,
    CONSTRAINT team_members_pkey PRIMARY KEY (team_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_by integer,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default",
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_activities_project_id
    ON public.activities(project_id);


ALTER TABLE IF EXISTS public.activities
    ADD CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT attachments_task_id_fkey FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attachments
    ADD CONSTRAINT attachments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comment_task FOREIGN KEY (entity_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comment_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.datasets
    ADD CONSTRAINT fk_dataset_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.datasets
    ADD CONSTRAINT fk_dataset_created_by FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.dataset_dependencies
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    source_dataset_id integer NOT NULL,
    target_dataset_id integer NOT NULL,
    task_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dataset_dependencies_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dd UNIQUE (source_dataset_id, target_dataset_id, task_id),
    CONSTRAINT fk_dd_source FOREIGN KEY (source_dataset_id)
        REFERENCES public.datasets (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_dd_target FOREIGN KEY (target_dataset_id)
        REFERENCES public.datasets (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_dd_task FOREIGN KEY (task_id)
        REFERENCES public.tasks (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dd_source ON public.dataset_dependencies(source_dataset_id);
CREATE INDEX IF NOT EXISTS idx_dd_target ON public.dataset_dependencies(target_dataset_id);
CREATE INDEX IF NOT EXISTS idx_dd_task ON public.dataset_dependencies(task_id);


ALTER TABLE IF EXISTS public.experiment_datasets
    ADD CONSTRAINT fk_ed_dataset FOREIGN KEY (dataset_id)
    REFERENCES public.datasets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.experiment_datasets
    ADD CONSTRAINT fk_ed_task FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grants
    ADD CONSTRAINT fk_grant_creator FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.grants
    ADD CONSTRAINT fk_grant_pi FOREIGN KEY (principal_investigator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.hypotheses
    ADD CONSTRAINT fk_hypothesis_creator FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.hypotheses
    ADD CONSTRAINT fk_hypothesis_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_grant_funding
    ADD CONSTRAINT fk_pgf_grant FOREIGN KEY (grant_id)
    REFERENCES public.grants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pgf_grant
    ON public.project_grant_funding(grant_id);


ALTER TABLE IF EXISTS public.project_grant_funding
    ADD CONSTRAINT fk_pgf_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pgf_project
    ON public.project_grant_funding(project_id);


ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_pm_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_pm_role FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.project_members
    ADD CONSTRAINT fk_pm_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_project_team FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_rp_role FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sprints
    ADD CONSTRAINT sprints_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.task_history
    ADD CONSTRAINT fk_task_history_changed_by FOREIGN KEY (changed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.task_history
    ADD CONSTRAINT task_history_task_id_fkey FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.task_tags
    ADD CONSTRAINT task_tags_tag_id_fkey FOREIGN KEY (tag_id)
    REFERENCES public.tags (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.task_tags
    ADD CONSTRAINT task_tags_task_id_fkey FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT fk_task_creator FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT fk_task_hypothesis FOREIGN KEY (hypothesis_id)
    REFERENCES public.hypotheses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT fk_task_project FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_sprint_id_fkey FOREIGN KEY (sprint_id)
    REFERENCES public.sprints (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.teams
    ADD CONSTRAINT teams_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;